<a href="https://colab.research.google.com/github/xXLukaENPXx/Algoritmos-2/blob/main/Practica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# =========================================
# 1. Import libraries
# =========================================
import pandas as pd
import numpy as np

# =========================================
# 2. Load the dataset
# =========================================
url = "https://raw.githubusercontent.com/ywchiu/riii/master/data/house-prices.csv"
df = pd.read_csv(url)

# =========================================
# 3. Initial exploration of the dataset
# =========================================

print("First 5 rows of the dataset:")
display(df.head())

print("\nDataset shape (rows, columns):")
print(df.shape)

print("\nList of columns:")
print(df.columns)

print("\nData types:")
print(df.dtypes)

print("\nSummary statistics:")
display(df.describe())

# Confirm the target variable
print("\nTarget variable:")
print("Price")

# =========================================
# 4. Identify uninformative columns
# =========================================
print("\nChecking possible ID-like columns:")
print(df.head())

# 'Home' is just an identifier for each house
# so it is not informative for prediction.

# =========================================
# 5. Data preprocessing
# =========================================

# ---- Remove unnecessary column
df = df.drop(columns=["Home"])

print("\nDataset after removing uninformative columns:")
display(df.head())

# ---- Check missing values
print("\nMissing values per column:")
print(df.isnull().sum())

# If missing values existed, we could handle them with:
# df = df.dropna()
# or
# df.fillna(df.mean())

# In this dataset normally there are no missing values.

# ---- Verify data types
print("\nData types after cleaning:")
print(df.dtypes)

# Convert categorical variables to numeric
df = pd.get_dummies(df, columns=["Brick", "Neighborhood"], drop_first=True)

print("\nDataset after encoding categorical variables:")
display(df.head())

# =========================================
# 6. Define X and y for modeling
# =========================================

y = df["Price"]          # Target variable
X = df.drop(columns=["Price"])  # Input features

print("\nShape of X:", X.shape)
print("Shape of y:", y.shape)

print("\nFeatures used for modeling:")
print(X.columns)

print("\nTarget variable preview:")
print(y.head())

First 5 rows of the dataset:

   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

Dataset shape (rows, columns):
(128, 8)

List of columns:
Index(['Home', 'Price', 'SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick',
       'Neighborhood'],
      dtype='object')

Data types:
Home             int64
Price            int64
SqFt             int64
Bedrooms         int64
Bathrooms        int64
Offers           int64
Brick           object
Neighborhood    object
dtype: object

Summary statistics:

,Home,Price,SqFt,Bedrooms,Bathrooms,Offers
count,128.000000,128.000000,128.000000,128.000000,128.000000,128.000000
mean,64.500000,130427.343750,2000.937500,3.023438,2.445312,2.578125
std,37.094474,26868.770371,211.572431,0.725951,0.514492,1.069324
min,1.000000,69100.000000,1450.000000,2.000000,2.000000,1.000000
25%,32.750000,111325.000000,1880.000000,3.000000,2.000000,2.000000
50%,64.500000,125950.000000,2000.000000,3.000000,2.000000,3.000000
75%,96.250000,148250.000000,2140.000000,3.000000,3.000000,3.000000
max,128.000000,211200.000000,2590.000000,5.000000,4.000000,6.000000

Target variable:
Price

Checking possible ID-like columns:
   Home   Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0     1  114300  1790         2          2       2    No         East
1     2  114200  2030         4          2       3    No         East
2     3  114800  1740         3          2       1    No         East
3     4   94700  1980         3          2       3    No         East
4     5  119800  2130         3          3       3    No         East

Dataset after removing uninformative columns:

    Price  SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0  114300  1790         2          2       2    No         East
1  114200  2030         4          2       3    No         East
2  114800  1740         3          2       1    No         East
3   94700  1980         3          2       3    No         East
4  119800  2130         3          3       3    No         East

Missing values per column:
Price           0
SqFt            0
Bedrooms        0
Bathrooms       0
Offers          0
Brick           0
Neighborhood    0
dtype: int64

Data types after cleaning:
Price            int64
SqFt             int64
Bedrooms         int64
Bathrooms        int64
Offers           int64
Brick           object
Neighborhood    object
dtype: object

Dataset after encoding categorical variables:

,Price,SqFt,Bedrooms,Bathrooms,Offers,Brick_Yes,Neighborhood_North,Neighborhood_West
0,114300,1790,2,2,2,False,False,False
1,114200,2030,4,2,3,False,False,False
2,114800,1740,3,2,1,False,False,False
3,94700,1980,3,2,3,False,False,False
4,119800,2130,3,3,3,False,False,False

Shape of X: (128, 7)
Shape of y: (128,)

Features used for modeling:
Index(['SqFt', 'Bedrooms', 'Bathrooms', 'Offers', 'Brick_Yes',
       'Neighborhood_North', 'Neighborhood_West'],
      dtype='object')

Target variable preview:
0    114300
1    114200
2    114800
3     94700
4    119800
Name: Price, dtype: int64

4

In [ ]:
# =========================================
# 4. Split the Dataset
# =========================================

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,   # 20% testing
    random_state=42
)

print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (102, 7)
Testing set shape: (26, 7)

5

In [ ]:
# =========================================
# 5. Feature Scaling
# =========================================

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Fit only on training data
X_train_scaled = scaler.fit_transform(X_train)

# Apply same transformation to test data
X_test_scaled = scaler.transform(X_test)

print("Feature scaling completed.")

Feature scaling completed.

6

In [ ]:
# =========================================
# 6. Create the Regression Model
# =========================================

from sklearn.linear_model import SGDRegressor

sgd_model = SGDRegressor(
    max_iter=1000,
    learning_rate='constant',
    eta0=0.01,
    random_state=42
)

print(sgd_model)

SGDRegressor(learning_rate='constant', random_state=42)

7

In [ ]:
# =========================================
# 7. Train the Model
# =========================================

sgd_model.fit(X_train_scaled, y_train)

print("Model training completed.")

Model training completed.

8

In [ ]:
# =========================================
# 8. Generate Predictions
# =========================================

y_pred = sgd_model.predict(X_test_scaled)

print("First predictions:")
print(y_pred[:5])

First predictions:
[117498.34712155  99977.26191335 160050.07921585 131805.37543819
 153108.65060897]

9

In [ ]:
# =========================================
# 9. Model Evaluation
# =========================================

from sklearn.metrics import mean_squared_error

mse = mean_squared_error(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)

Mean Squared Error (MSE): 112956498.76092488